- name: Inintialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
     chdir: $HOME
     creates: cluster_initialized.txt

- name: Create .kube directory
  become: yes
  file:
     path: $HOME/.kube
     state: directory
     mode: 0755

- name: Check admin.conf file exists.
  stat:
     path: /etc/kubernetes/admin.conf
  register: k8s_conf

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
  when: k8s_conf.stat.exists

- name: Install Pod network
  become: yes
  shell: kubectl apply -f "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml" >> pod_network_setup.txt
  args:
     chdir: $HOME
     creates: pod_network_setup.txt
